apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"techtrends","namespace":"prod"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"techtrends"}},"template":{"metadata":{"labels":{"app":"techtrends"}},"spec":{"containers":[{"image":"hankim2024/techtrends:latest","livenessProbe":{"httpGet":{"path":"/healthz","port":3111}},"name":"techtrends","ports":[{"containerPort":3111,"protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/healthz","port":3111}},"resources":{"limits":{"cpu":"500m","memory":"128Mi"},"requests":{"cpu":"250m","memory":"64Mi"}}}]}}}}
  creationTimestamp: "2024-12-11T20:29:45Z"
  generation: 5
  name: techtrends
  namespace: prod
  resourceVersion: "69734"
  uid: 1d6257f2-5187-4018-bc41-d7bcfd841986
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: techtrends
    spec:
      containers:
      - image: hankim2024/techtrends:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3111
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: techtrends
        ports:
        - containerPort: 3111
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3111
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-12-12T15:20:18Z"
    lastUpdateTime: "2024-12-12T15:20:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-12-12T15:47:11Z"
    lastUpdateTime: "2024-12-12T16:52:01Z"
    message: ReplicaSet "techtrends-d67b4689b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
