apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.service.port | default 4111 }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      targetPort: {{ .Values.service.targetPort | default 3111 }}
  selector:
    app: techtrends
  type: {{ .Values.service.type | default "ClusterIP" }}
