apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: argocd-server
  name: argocd-server-nodeport
  namespace: argocd
spec:
  type: NodePort
  ports:
  - name: https
    port: 443
    targetPort: 8080
    nodePort: 30008
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30007
  selector:
    app.kubernetes.io/name: argocd-server
