apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  labels:
    app: techtrends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: hankim2024/techtrends:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3111
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
      imagePullSecrets:
      - name: regcred
