namespace: prod

service:
  port: 7111

replicaCount: 5

resources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    memory: "256Mi"
    cpu: "500m"
    
livenessProbe:
  path: /healthz
  port: 7111  # For prod
readinessProbe:
  path: /healthz
  port: 7111  # For prod