namespace: staging

service:
  port: 3111

replicaCount: 3

resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"

livenessProbe:
  path: /healthz
  port: 3111
readinessProbe:
  path: /healthz
  port: 3111

